image:
  file: .gitpod.Dockerfile
  context: mycontext

ports:
  - port: 8080
    onOpen: open-preview
  - port: 9000
    onOpen: ignore

tasks:
  - init: echo initialize
  - command: nginx && multitail /var/log/nginx/access.log -I /var/log/nginx/error.log
  - command: /usr/sbin/php-fpm7.4 --fpm-config /etc/php/7.4/fpm/php-fpm.conf
